apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: db-env-config
    literals:
      - HOSTNAME=p-fg3vlurihj-rw-external-ce08a614c0dd6ca2.elb.us-west-2.amazonaws.com
      - USERNAME=edb_admin
      - PASSWORD=mattdemo123!
      - DATABASE=edb_admin

patches:
  - path: toleration-patch.yaml
    target:
      kind: Deployment
      name: os-db-json-tester
