apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: db-env-config
    literals:
      - HOSTNAME=hostname
      - USERNAME=username
      - PASSWORD=password
      - DATABASE=dbname

patches:
  - path: toleration-patch.yaml
    target:
      kind: Deployment
      name: os-db-json-tester
