apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-db-json-tester
spec:
  template:
    spec:
      tolerations:
      - key: "edbaiplatform.io/postgres"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
